#################################
## Configuration for other lsp ##
#################################

[language-server.harper]
command = "harper-ls"
args = ["--stdio"]

[language-server.clangd]
command = "clangd"
args = ["--enable-config"]

#################################
## Configuration for languages ##
#################################
## Every file type we intend to chat in needs to have lsp-ai enabled 
#source: https://github.com/helix-editor/helix/blob/master/languages.toml

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = [".yaml"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]
formatter = { command = 'deno', args = [
  "fmt",
  "-",
  "--ext",
  "md",
  "--line-width",
  "80",
] }
auto-format = true

[[language]]
name = "nix"
language-servers = ["nil"]
formatter = { command = "nixfmt" }
auto-format = true

#######################################
## Configuration for main languages ###
#######################################

[[language]]
name = "python"
language-servers = ["pyright", "ruff", "harper", "lsp-ai"]
formatter = { command = "ruff", args = ["format", "-", "--line-length", "80"] }
auto-format = true

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer", "harper", "lsp-ai"]

[[language]]
name = "haskell"
language-servers = ["haskell-language-server", "harper", "lsp-ai"]
formatter = { command = "stylish-haskell", args = [] }
auto-format = true

[[language]]
name = "c"
language-servers = ["clangd", "harper", "lsp-ai"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'clang-format' }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "harper", "lsp-ai"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
language-servers = ["clangd", "harper", "lsp-ai"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'clang-format' }
auto-format = true
