##############################
## Configuration for lsp-ai ##
##############################

[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = {}

[language-server.lsp-ai.config.models.model1]
type = "open_ai"
# chat_endpoint = "https://api.groq.com/openai/v1/chat/completions"
# model = "llama-3.1-8b-instant"
# auth_token = "GROQ_API_KEY"
chat_endpoint = "https://api.mistral.ai/v1/chat/completions"
model = "devstral-small-2505"
auth_token = "MISTRAL_API_KEY"

[[language-server.lsp-ai.config.actions]]
action_display_name = "Complete"
model = "model1"

## Configure the messages per your needs
[[language-server.lsp-ai.config.actions.parameters.messages]]
role = "system"
content = """
Instructions:
- You are an AI programming assistant.
- The user provides a code snippet with the cursor position marked by "<CURSOR>".
- Your task is to replace "<CURSOR>" with the correct code or comment.
- First, think step-by-step.
- Write a detailed plan in pseudocode explaining what should be built at the cursor location.
- Then output only the code that replaces "<CURSOR>".

Rules:
- Only output code or comments — no explanations, no markdown, no extra text.
- Do NOT include "<CURSOR>" in your output.
- Only output the replacement — do not include any code before or after "<CURSOR>".
- If the cursor is inside a comment, continue the comment naturally and meaningfully.
- Use the correct syntax for the language of the given snippet (e.g., Python, JavaScript, Rust).
- In ambiguous cases, choose the most contextually appropriate and consistent completion.
"""

[[language-server.lsp-ai.config.actions.parameters.messages]]
role = "user"
content = "{CODE}"
