#
# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '

# Zellij autostart disabled to test side-panel rendering without it.
# Re-enable by uncommenting the block below.
# if [[ -z "$ZELLIJ" ]]; then
#   zellij
# fi
