[go-home]
mon = [{ after = '17:30', before = '4:00' }]
tue = [{ after = '17:30', before = '4:00' }]
wed = [{ after = '17:30', before = '4:00' }]
thu = [{ after = '17:30', before = '4:00' }]
fri = [{ after = '17:30', before = '4:00' }]
sat = [{ after = '17:30', before = '4:00' }]
sun = [{ after = '17:30', before = '4:00' }]

[not-social-networks]
mon = [{ after = '4:00', before = '12:00' }]
tue = [{ after = '4:00', before = '12:00' }]
wed = [{ after = '4:00', before = '12:00' }]
thu = [{ after = '4:00', before = '12:00' }]
fri = [{ after = '4:00', before = '12:00' }]
sat = [{ after = '4:00', before = '12:00' }]
sun = [{ after = '4:00', before = '12:00' }]
