[work-focus]
mon = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]
tue = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]
wed = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]
thu = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]
fri = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]
sat = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]
sun = [
  { after = '07:00', before = '18:30' },
  { after = '19:30', before = '21:30' },
]

[no-youtube]
mon = [{ after = '07:00', before = '18:30' }]
tue = [{ after = '07:00', before = '18:30' }]
wed = [{ after = '07:00', before = '18:30' }]
thu = [{ after = '07:00', before = '18:30' }]
fri = [{ after = '07:00', before = '18:30' }]
sat = [{ after = '07:00', before = '18:30' }]
sun = [{ after = '07:00', before = '18:30' }]

[go-home]
mon = [{ after = '05:00', before = '17:30' }]
tue = [{ after = '05:00', before = '17:30' }]
wed = [{ after = '05:00', before = '17:30' }]
thu = [{ after = '05:00', before = '17:30' }]
fri = [{ after = '05:00', before = '17:30' }]
sat = [{ after = '05:00', before = '17:30' }]
sun = [{ after = '05:00', before = '17:30' }]
