[time-to-sleep]
mon = [{ after = '20:00', before = '6:00' }]
tue = [{ after = '21:00', before = '6:00' }]
wed = [{ after = '20:00', before = '6:00' }]
thu = [{ after = '20:00', before = '6:00' }]
fri = [{ after = '20:00', before = '6:00' }]
sat = [{ after = '20:00', before = '6:00' }]
sun = [{ after = '20:00', before = '6:00' }]

[work]
mon = [{ after = '6:00', before = '18:00' }]
tue = [{ after = '6:00', before = '18:00' }]
wed = [{ after = '6:00', before = '18:00' }]
thu = [{ after = '6:00', before = '18:00' }]
fri = [{ after = '6:00', before = '18:00' }]
sat = [{ after = '6:00', before = '18:00' }]
sun = [{ after = '6:00', before = '18:00' }]
