# [schedules]

[schedules.time-to-sleep]
mon = [{ after = '21:00', before = '7:00' }]
tue = [{ after = '21:00', before = '7:00' }]
wed = [{ after = '21:00', before = '7:00' }]
thu = [{ after = '21:00', before = '7:00' }]
fri = [{ after = '23:00', before = '7:00' }]
sat = [{ after = '23:00', before = '7:00' }]
sun = [{ after = '21:00', before = '7:00' }]

[schedules.work]
mon = [{ after = '9:00', before = '18:00' }]
tue = [{ after = '9:00', before = '18:00' }]
wed = [{ after = '9:00', before = '18:00' }]
thu = [{ after = '9:00', before = '18:00' }]
fri = [{ after = '9:00', before = '17:00' }]
